[Week4] XML 필수 과제
NOW-SOPT-ANDROID/arin-kim pull request #11
Opened 2024-05-03 06:00 UTC by arinming

### 🧩 Issue number
이슈 번호 : #9 

### ✨ Summary
MVVM 패턴에서 StateFlow를 활용하여 통신을 구현하였습니다.
- 회원가입 로직
- 로그인 로직
- 회원정보 조회 로직
- Interceptor

### 🔍 PR Type
- [x] 필수 XML
- [ ] 필수 Compose
- [ ] 심화 XML
- [ ] 심화 Compose
- [ ] 도전 XML
- [ ] 도전 Compose

### 📷 Screenshot

https://github.com/NOW-SOPT-ANDROID/arin-kim/assets/97820109/a99ae2dc-f5c3-489b-9477-8004d2681821

### 📔 Other Information

Interceptor로 리퀘스트 헤더에 memberId 넣을 때
로컬에 있는 userId로 넣으려고 SharedPreference, Data Store 등 열심히 공부해봤는데
아무리 해도 모르곘어요.....ㅠㅠㅠㅠ

2024-05-05 08:21 UTC, yeonjeen reviewed
수고하셨습니당:) 여행 잘 다녀오세용

2024-05-05 08:21 UTC, yeonjeen commented on app/build.gradle
>  }
크으 깔끔한거 보소.. 나도 배워야겠당 ㅎㅎ

2024-05-05 08:21 UTC, yeonjeen commented on app/src/main/java/com/sopt/now/ui/home/viewModel/HomeViewModel.kt
> +
여기에서 suspend와 코루틴을 이용하면 콜백을 이용하지 않고도 비동기 처리가 가능할까요?

2024-05-05 08:21 UTC, yeonjeen commented on app/src/main/java/com/sopt/now/ui/home/viewModel/HomeViewModel.kt
> +        }
여기서 map 함수를 사용해보시는 건 어떨까요?

2024-05-05 08:21 UTC, yeonjeen commented on app/src/main/java/com/sopt/now/ui/signIn/SignInActivity.kt
> +    }
진짜 저세상 깔끔한 코드쓰 짱

2024-05-05 09:30 UTC, SYAAINN reviewed
ViewModel 분리와 함수화가 돋보이는 코드였던 것 같아요. 보기도 편하고 뭔가 기초가 단단히 잡혀있는 느낌?! 잘 보고갑니다 ㅎㅎ

2024-05-05 09:30 UTC, SYAAINN commented on app/src/main/java/com/sopt/now/data/model/ResponseUserDto.kt
SerialName 어노테이션이 붙은 것과 안붙은 것에 어떤 기능적 차이가 있을까요?

2024-05-05 09:30 UTC, SYAAINN commented on app/src/main/java/com/sopt/now/data/network/AuthService.kt
> +    ): Call<ResponseInfoDto>
이 함수 구현이 비어있는데 작동하나요,,? 안된다면 @Header 어노테이션을 이용해서 작성하면 좋을 것 같습니다!

2024-05-05 09:30 UTC, SYAAINN commented on app/src/main/java/com/sopt/now/data/module/ApiFactory.kt
> +            .client(interceptorClient)
인터셉터 활용 시도하셨군요!

2024-05-05 09:30 UTC, SYAAINN commented on app/src/main/java/com/sopt/now/ui/adapter/ItemAdapter.kt
> +                    .into(holder.profileImage)
Glide..! 처음보는 친군데 공부해봐야겠네요. 혹시 역할을 간단하게 알 수 있을까요?

2024-05-05 09:30 UTC, SYAAINN commented on app/src/main/java/com/sopt/now/ui/signIn/SignInActivity.kt
> +        setSignUpButtonClickListeners()
함수화 너무 편안해요 like 시몬스,,

2024-05-05 09:30 UTC, SYAAINN commented on app/src/main/java/com/sopt/now/ui/signUp/SignUpActivity.kt
> +                else -> showToastMessage("모든 정보를 입력해주세요.")
when을 사용하니까 코드가 한층 더 깔끔해보여요!

2024-05-05 09:30 UTC, SYAAINN commented on app/src/main/java/com/sopt/now/ui/signUp/SignUpActivity.kt
> +                && Regex("^(?=.*[A-Za-z])(?=.*[0-9])(?=.*[\$@!%*#?&.])[A-Za-z[0-9]\$@!%*#?&.]{8,20}\$").matches(
정규식 활용 ㄷㄷㄷ.. 이번 코틀린 스터디에서 공부했던 부분이라 적용할 수 있을거 같다고 생각했는데 이렇게 마주치게 되니까 반갑네요

2024-05-05 09:30 UTC, SYAAINN commented on app/src/main/java/com/sopt/now/ui/signUp/SignUpActivity.kt
> +        return phoneNumberText.isNotBlank() && Regex("^010-\\d{4}-\\d{4}\$").matches(phoneNumberText)
코틀린은 불필요한 역슬래시를 줄이기 위해 어떤 기능을 지원하고 있는데요! 어떤 것일까요 ㅎㅎ

2024-05-05 14:46 UTC, junseo511 approved these changes
함수정리도 엄청 열심히 하시고, 전반적으로 가독성을 높이려고 하는 시도가 보여서 멋있습니다 👍👍 이대로면 조만간 놀라울 정도로 강해지실지도?!

2024-05-05 14:46 UTC, junseo511 commented on app/build.gradle
> +    annotationProcessor 'com.github.bumptech.glide:compiler:4.13.0'
정리 깔끔해서 보기 좋습니다~~

2024-05-05 14:46 UTC, junseo511 commented on app/build.gradle
> +    implementation 'org.jetbrains.kotlinx:kotlinx-serialization-json:1.5.1'
근데 이친구는 retrofit이 아닌거같아용

2024-05-05 14:46 UTC, junseo511 commented on app/src/main/java/com/sopt/now/data/model/ResponseUserDto.kt
> +)
굉장히 섬세하게 분리를 하셨네요 ㄷㄷ

2024-05-05 14:46 UTC, junseo511 commented on app/src/main/java/com/sopt/now/data/model/SignInState.kt
> +)
state를 data class로 처리하신 이유가 있으실까요?~!
틀린건 아니구 궁금해서!!!

2024-05-05 14:46 UTC, junseo511 commented on app/src/main/java/com/sopt/now/data/module/ApiFactory.kt
> +    }
이친구 예쁘게 합칠 수 있을 것 같슴당

2024-05-05 14:46 UTC, junseo511 commented on app/src/main/java/com/sopt/now/data/module/AuthInterceptor.kt
> +            .addHeader("memberId", "495")
ㅋㅋㅋㅋㅋㅋㅋ "495" 이친구 공유할 방법이 있을까요?!
인터셉트 좋슴당

2024-05-05 14:46 UTC, junseo511 commented on app/src/main/java/com/sopt/now/ui/adapter/ItemAdapter.kt
> +                    .into(holder.profileImage)
대표적으로 쓰이는 이미지 로드 라이브러리입니다!! Coil도 있어용 함께 알아보시죠

2024-05-05 14:46 UTC, junseo511 commented on app/src/main/java/com/sopt/now/ui/home/HomeFragment.kt
> +            repeatOnLifecycle(Lifecycle.State.STARTED) {
이친구의 역할은 뭔가요?!

2024-05-05 14:46 UTC, junseo511 commented on app/src/main/java/com/sopt/now/ui/home/viewModel/HomeViewModel.kt
> +                        _followerState.value = data
state 관리하려고 하는 모습 아주 좋습니다~~!!

2024-05-05 14:46 UTC, junseo511 commented on app/src/main/java/com/sopt/now/ui/myPage/MyPageFragment.kt
> +    }
이친구 너무 장풍쏘는거같아요 ㅋㅋㅋㅋㅋㅋㅋㅋ

2024-05-05 14:46 UTC, junseo511 commented on app/src/main/java/com/sopt/now/ui/signUp/SignUpActivity.kt
> +                && Regex("^(?=.*[A-Za-z])(?=.*[0-9])(?=.*[\$@!%*#?&.])[A-Za-z[0-9]\$@!%*#?&.]{8,20}\$").matches(
API에서 검증을 해주는데 저희가 또 검증을 거치는 것이 좋을까요?

아니면 API를 믿고 검증을 거치지 않는 것이 나을까요?

2024-05-05 14:46 UTC, junseo511 requested changes
아! 리팩 완료하시고 말씀해주시면 어푸해드릴게용

2024-05-06 14:27 UTC, briandr97 requested changes
안녕하세요 아린님, 아린님의 리뷰어를 맡게된 권용민이라고 합니다!

필수 과제에 `xml`과 `compose`가 있는데요 `xml`은 제가, `compose`는 준원님께서 리뷰해주실 예정입니다.
코드에 정답이 없으며, 저희 또한 많이 부족한 사람이므로 공통 로직에서 저와 준원님의 의견이 상충될 수 있습니다. 혹시 그런 상황이 발생한다면, 아린님께서 생각하시는대로 진행하고 말씀해주시면 됩니다!

또 제가 리뷰해드린 내용이라고 해서 정답은 아닙니다. 사람마다 생각이 다를 수 있으며, 제가 틀렸을 수도 있습니다. 납득이 되지 않으면 언제든 질문주시고, 아린님의 생각을 말씀해주세요!

과제하느라 고생하셨습니다! 잘부탁드립니다!

모든 리뷰에 1~5에 해당하는 번호를 남겼습니다. 해당 번호들은 중요도를 나타냅니다.
1,2번은 changes requested,
3번은 comment,
4,5번은 추가정보 정도로 생각해주시면 좋을 것 같습니다.

2024-05-06 14:27 UTC, briandr97 commented on app/src/main/java/com/sopt/now/data/module/AuthInterceptor.kt
> +            .addHeader("memberId", "495")
안드로이드에서 가장 쉽게 활용해볼 수 있는 저장소로 [sharedPreferences](https://developer.android.com/training/data-storage/shared-preferences?hl=ko)가 있습니다.

데이터를 영속적으로 저장하고 사용해봐도 좋을 것 같습니다.
(`DataStore`가 더 권장되는 최신 방법이지만, 학습 곡선이 비교적 더 높은 관계로 우선 `SharedPreferences`를 추천드립니다.)

2024-05-06 14:27 UTC, briandr97 commented on app/src/main/java/com/sopt/now/ui/home/HomeFragment.kt
> +    }
[1]
MVVM은 View가 ViewModel을 관찰하는 구조입니다.
그래서 뷰모델의 상태를 구독중이신 것 같습니다.
그렇다면 왜 `collect`를 통해 전달 받은 상태를 사용하지 않고 다시 뷰모델의 상태를 참조해서 사용할까요?

2024-05-06 14:27 UTC, briandr97 commented on app/src/main/java/com/sopt/now/ui/home/HomeFragment.kt
> +    }
[1]
만약 "새로고침" 기능이 생겨서 뷰모델의 상태가 자주 업데이트 된다고 한다면 어떤 문제가 발생할 수 있을까요?

2024-05-06 14:27 UTC, briandr97 commented on app/src/main/java/com/sopt/now/ui/home/viewModel/HomeViewModel.kt
> +    val followerState = _followerState.asStateFlow()
[3]
변수명을 followerState로 작성한 이유가 있을까요?
유저 정보들인 것으로 보아 `users`가 더 직관적이지 않을까 생각해봤습니다.

2024-05-06 14:27 UTC, briandr97 commented on app/src/main/java/com/sopt/now/ui/home/viewModel/HomeViewModel.kt
>  class HomeViewModel : ViewModel() {
[5]
ViewModel 내부에 안드로이드 종속성과 레트로핏과 같은 외부 라이브러리 종속성들이 들어있는데, 추후 어떤 문제가 발생할 수 있을까요?

2024-05-06 14:27 UTC, briandr97 commented on app/src/main/java/com/sopt/now/ui/home/viewModel/HomeViewModel.kt
> +                        Log.d("FOLLOWER", "$data")
[5]
개발 과정에서 작성한 로그는 지우는 습관을 가지면 좋습니다.

2024-05-06 14:27 UTC, briandr97 commented on app/src/main/java/com/sopt/now/ui/home/viewModel/HomeViewModel.kt
> +        }
[3]
공감합니다. `map`함수를 알아보면 좋을 것 같습니다.
`map`함수뿐만 아니라 코틀린 컬렉션 확장함수들에는 굉장히 다양한 것들이 있습니다. 추가로 알아보시면 코드를 작성하실 때 훨씬 간결해질겁니다.

2024-05-06 14:27 UTC, briandr97 commented on app/src/main/java/com/sopt/now/ui/signIn/viewModel/SignInViewModel.kt
> +        )
[4]
비슷한 코드가 여러 뷰모델에서 보입니다.
제네릭의 특성을 살려서 하나의 함수로 줄여볼 수도 있을 것 같아요.

2024-05-06 14:27 UTC, briandr97 commented on app/src/main/java/com/sopt/now/ui/signUp/viewModel/SignUpViewModel.kt
> +                                message = "가입된 유저 아이디는 $userId"
[2]
텍스트를 `strings.xml`에서 관리하는 기준이 어떻게 될까요?
어떤 문자는 `strings.xml`에서 관리하고 어떤 문자는 하드코딩할까요?

2024-05-23 11:31 UTC, arinming reviewed
흑흑 늦어서 죄송해요 🥺🥺🥺🥺🥺🥺🥺🥺🥺🥺 다들 섬세한 리뷰 너무 감사합니다 후딱 리팩토링 하고 6차 과제까지 쇼록 해보겠습니다1!!!!!

2024-05-23 11:31 UTC, arinming commented on app/build.gradle
> +    implementation 'org.jetbrains.kotlinx:kotlinx-serialization-json:1.5.1'
눈썰미 👀

2024-05-23 11:31 UTC, arinming commented on app/src/main/java/com/sopt/now/data/model/ResponseUserDto.kt
Kotlin 데이터 클래스의 속성명을 JSON 등의 직렬화된 형식에서 사용할 이름과 매핑할 때 사용하는 것으로 알고 있습니다~!

2024-05-23 11:31 UTC, arinming commented on app/src/main/java/com/sopt/now/data/model/SignInState.kt
> +)
데이터 모델임을 확실히 명시하고,,, 음 사실 데이터 클래스가 훨씬 익숙해서 쓴 것 같습니다.! 다른 방법도 있을까욤?

2024-05-23 11:31 UTC, arinming commented on app/src/main/java/com/sopt/now/data/module/AuthInterceptor.kt
> +            .addHeader("memberId", "495")
SharedPreferences로 로컬 데이터 저장해보겠습니당!

2024-05-23 11:31 UTC, arinming commented on app/src/main/java/com/sopt/now/data/network/AuthService.kt
> +    ): Call<ResponseInfoDto>
와 이 기능은 처음알았어요! 감사해요

2024-05-23 11:31 UTC, arinming commented on app/src/main/java/com/sopt/now/ui/adapter/ItemAdapter.kt
> +                    .into(holder.profileImage)
이번에 합세하면서 Coil도 적용해보았는데 어떤 차이가 있는지 공부해보겠습니다!

2024-05-23 11:31 UTC, arinming commented on app/src/main/java/com/sopt/now/ui/home/HomeFragment.kt
> +            repeatOnLifecycle(Lifecycle.State.STARTED) {
프래그먼트가 시작될 때마다 코루틴이 실행되도록 하는 함수입니다!

2024-05-23 11:31 UTC, arinming commented on app/src/main/java/com/sopt/now/ui/home/HomeFragment.kt
> +    }
> [1] MVVM은 View가 ViewModel을 관찰하는 구조입니다. 그래서 뷰모델의 상태를 구독중이신 것 같습니다. 그렇다면 왜 `collect`를 통해 전달 받은 상태를 사용하지 않고 다시 뷰모델의 상태를 참조해서 사용할까요?

뷰모델 상태가 변경될 떄마다 UI가 업데이트 되기 때문인 것 같습니다..! 혹시 제가 잘못알고 있다면 좋은 정보 알려주시면 감사하겠습니다 🥹🙏🏻🥹🙏🏻

2024-05-23 11:31 UTC, arinming commented on app/src/main/java/com/sopt/now/ui/home/HomeFragment.kt
> +    }
> [1] 만약 "새로고침" 기능이 생겨서 뷰모델의 상태가 자주 업데이트 된다고 한다면 어떤 문제가 발생할 수 있을까요?

리사이클러뷰가 계속 새로운 데이터를 갱신해야 해서 성능상 안좋고, 새로운 데이터가 뷰모델에 업데이트 되어 중복 항목이 추가될 수 있다고 하네용...! 🫨

2024-05-23 11:31 UTC, arinming commented on app/src/main/java/com/sopt/now/ui/home/viewModel/HomeViewModel.kt
>  class HomeViewModel : ViewModel() {
뷰모델에 종속성이 포함되면 메모리 누수가 발생할 수 있다고 하네용..! Repository로 관리하도록 리팩토링 하겠습니다!

2024-05-23 11:31 UTC, arinming commented on app/src/main/java/com/sopt/now/ui/home/viewModel/HomeViewModel.kt
> +    val followerState = _followerState.asStateFlow()
훨씬 깔끔하고 직관적이네요..! 수정하겠스니당.

2024-05-23 11:31 UTC, arinming commented on app/src/main/java/com/sopt/now/ui/home/viewModel/HomeViewModel.kt
> +                        Log.d("FOLLOWER", "$data")
넵! 감사합니다!

2024-05-23 11:31 UTC, arinming commented on app/src/main/java/com/sopt/now/ui/home/viewModel/HomeViewModel.kt
> +
넹 retrofit을 사용하면서 suspend 함수를 호출하고 viewModelScope.launch로 비동기 실행이 가능할 것 같아요..! 근데 너무 어렵다.....

2024-05-23 11:31 UTC, arinming commented on app/src/main/java/com/sopt/now/ui/home/viewModel/HomeViewModel.kt
> +        }
헉 간결하고 직관적이네용....! 바로 적용하도록 하겠습니당.

2024-05-23 11:31 UTC, arinming commented on app/src/main/java/com/sopt/now/ui/signUp/SignUpActivity.kt
> +        return phoneNumberText.isNotBlank() && Regex("^010-\\d{4}-\\d{4}\$").matches(phoneNumberText)
어머 원시문자열 """ 활용하면 도ㅒㅆ군요!!!!! 알아갑니다 ㅜㅜㅜ

2024-05-23 11:31 UTC, arinming commented on app/src/main/java/com/sopt/now/ui/signUp/SignUpActivity.kt
> +                && Regex("^(?=.*[A-Za-z])(?=.*[0-9])(?=.*[\$@!%*#?&.])[A-Za-z[0-9]\$@!%*#?&.]{8,20}\$").matches(
아핫 애초에 서버에서 검증을 해주면 정규식 활용이 굳이 필요 없겠네요! 코드가 오히려 어려워 보이는....

2024-05-23 11:31 UTC, arinming commented on app/src/main/java/com/sopt/now/ui/signUp/viewModel/SignUpViewModel.kt
> +                                message = "가입된 유저 아이디는 $userId"
동적 텍스트는 코드에서 직접 관리하고, 정적 텍스트를 strings.xml에서 관리하는 것으로 알고 있습니다!

2024-05-23 11:31 UTC, arinming commented on app/src/main/java/com/sopt/now/ui/signIn/viewModel/SignInViewModel.kt
> +        )
헉 베이스 뷰모델을 사용하는게 좋을까요!? 깊이있는 공부가 필요해 보이네용 열심히 알아보겠습니다!

2024-06-07 12:21 UTC, merged