[Week4] Compose 필수 과제
NOW-SOPT-ANDROID/arin-kim pull request #12
Opened 2024-05-03 07:52 UTC by arinming

### 🧩 Issue number
이슈 번호 : #10 

### ✨ Summary
컴포즈는 XML 뷰모델 그대로 쓰고, Screen 로직만 변경했어요
XML에 시간 많이 쓴 만큼.... 컴포즈는 수월했던 것 같ㅌ습니다

### 🔍 PR Type
- [ ] 필수 XML
- [x] 필수 Compose
- [ ] 심화 XML
- [ ] 심화 Compose
- [ ] 도전 XML
- [ ] 도전 Compose

### 📷 Screenshot

https://github.com/NOW-SOPT-ANDROID/arin-kim/assets/97820109/d6a6daaf-59e7-4108-81ea-8d5f4d1a0acc

### 📔 Other Information
인터셉트 너무 어렵지만 일단 피알 올리고 천천히 공부해보겠습니다 ㅜㅜ!!!!!!!! 팟팅.

2024-05-05 09:41 UTC, SYAAINN reviewed
전체적으로 xml 과 동일하네요! 얼른 같이 인터셉터 마스터해서 구현 완료해봅시다!

2024-05-05 09:41 UTC, SYAAINN commented on app/build.gradle
>  }
처음부터 모르는 녀석이 등장.. Coil 이 어떤 기능일까요?

2024-05-05 09:41 UTC, SYAAINN commented on app/src/main/java/com/sopt/now/compose/data/module/AuthInterceptor.kt
> +            .build()
인터셉터 기능 활용이 잘 안돼서 멤버아이디를 강제로 집어넣은걸까요??

2024-05-05 09:41 UTC, SYAAINN commented on app/src/main/java/com/sopt/now/compose/ui/signUp/SignUpScreen.kt
> +                id.length in 6..10 && password.length in 8..12 && nickname.isNotEmpty() && !nickname.contains(
우리 상수들은 이제 그만.. 놓아주는 건 어떨까요?! ㅋㅋㅋㅋㅋ

2024-05-05 14:52 UTC, junseo511 approved these changes
xml에서 한번 진행되고 오니까 쉽죠?!
이게 뷰모델의 힘입니다~~👍
저희 한번 이제 비동기처리랑 코루틴이라는 부분을  천천히 배워볼까요 🤭

2024-05-05 14:52 UTC, junseo511 commented on app/build.gradle
> +    implementation 'io.coil-kt:coil-compose:2.6.0'
둘다 추가하신 이유가 있나요?

2024-05-05 14:55 UTC, yeonjeen reviewed
역시 컴포즈 장인!! 항상 좋은 코드 보고 많이 배워갑니다~

2024-05-05 14:55 UTC, yeonjeen commented on app/build.gradle
> +    annotationProcessor 'com.github.bumptech.glide:compiler:4.13.0'
glide랑 coil 둘 다 사용하신 건가용??

2024-05-05 14:55 UTC, yeonjeen commented on app/src/main/java/com/sopt/now/compose/ui/home/HomeViewModel.kt
> +    private val followerService by lazy { ServicePool.followerService }
필요할 때만 초기화 할 수 있어서 좋은 것 같아용 짱!!

2024-05-05 14:55 UTC, yeonjeen commented on app/src/main/java/com/sopt/now/compose/ui/home/HomeViewModel.kt
> +            )
저도 시도해보지는 않았지만 데이터 매핑 로직은 util 클래스로 분리하는게 좋다고 들어서 나중에 같이 도전해봐용:)

2024-05-05 14:55 UTC, yeonjeen commented on app/src/main/java/com/sopt/now/compose/ui/signUp/SignUpViewModel.kt
> +    private val _signUpState = MutableStateFlow(SignUpState(isSuccess = false, message = ""))
보면 livedata 보다는 state를 사용하시는 편이신데 이유가 있으실까요?

2024-05-06 17:01 UTC, murjune requested changes
안녕하세요. 아린님 리뷰어로 함께하게 된 명예OB 이준원입니다. 앞으로 잘 부탁드립니다.

양이 상당히 많았을 텐데 과제 구현하시느라 고생하셨습니다!  
제가 활동 기수였다면.. 저는 못했을 것 같아요 너무 대단하십니다 👍👍👍  

저는 개발자라면 내가 작성한 코드에 대해 남에게 설명할 수 있어야한다고 생각해요  
그래서, 단순한 지식 공유 보다는 ~~물음표 살인마~~ 로 아린님이 어떤 의도로 코드를 작성하신 것인지구체적으로 질문을 드렸습니다.  

제가 남겨드린 코멘트를 모두 반영하지 않아도 좋아요!!   
아린님이 판단하기에 `나 이 정도면 많이 성장했다!` 라고 생각하실 때 머지하셔도 됩니다 :D

---  

개인적으로 [객체지향의 사실과 오해](https://m.yes24.com/Goods/Detail/18249021) 라는 책을 추천드려요! 객체지향적인 사고를 하시데 많은 도움이 될 겁니다 💪

2024-05-06 17:01 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/ui/signUp/SignUpScreen.kt
> +                ) && phone.matches(Regex("^010-\\d{4}-\\d{4}\$"))
유효성 검사는 viewmodel 에서 해야하지 않을까요?

2024-05-06 17:01 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/ui/signUp/SignUpScreen.kt
> +                ) && phone.matches(Regex("^010-\\d{4}-\\d{4}\$"))
서버 통신하기 전에, 내부적으로 유효성 검사 좋네요 👍

2024-05-06 17:01 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/ui/signUp/SignUpViewModel.kt
> +                    response: Response<ResponseSignUpDto>,
매 번 서버 통신을 할 때마다, Callback 의 익명 객체를 만들어주고 있는데요..!
함수 or 객체로 분리할 수 있을까요??

2024-05-06 17:01 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/ui/signUp/SignUpViewModel.kt
> +                }
400.. 500 번대의 모든 에러가 해당 에러 메세지를 보여줄텐데요..  

사용자에게 어떤 이유로 회원가입에 실패했는지 case 마다 알려줄 수 있을까요??  

ex1. 정해진 id 양식이 아닙니다
ex2. 닉네임에 빈값을 넣을 수 없습니다

2024-05-06 17:01 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/ui/signUp/SignUpViewModel.kt
> +    private val _signUpState = MutableStateFlow(SignUpState(isSuccess = false, message = ""))
- LiveData 가 아닌 StateFlow 를 사용하신 이유가 있을까요?
- StateFlow 를 사용함으로써 얻을 수 있는 이점이 무엇일까요?

2024-05-06 17:01 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/ui/signUp/SignUpViewModel.kt
> +    private val _signUpState = MutableStateFlow(SignUpState(isSuccess = false, message = ""))
error mesage 와 success message 를 분리해보는건 어떨까요?

2024-05-06 17:01 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/ui/signUp/SignUpViewModel.kt
> +    private val _signUpState = MutableStateFlow(SignUpState(isSuccess = false, message = ""))
현재 동일한 error 가 중복해서 발생할 경우에는 View 로 Event가 전달되지 않고 있어요..!  

어떻게 개선해볼 수 있을까요?

https://github.com/NOW-SOPT-ANDROID/arin-kim/assets/87055456/6ff02f1b-50e4-4fc9-b448-92a255188769

2024-05-06 17:01 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/ui/signUp/SignUpViewModel.kt
> +    private val authService by lazy { ServicePool.authService }
by lazy를 사용하신 이유가 있을까요?

2024-05-06 17:01 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/ui/signUp/SignUpScreen.kt
> +            onNavigateToSignIn.navigate("sign_in")
- 상수화를 해주세요..!  
- 상수화를 해주면 어떤 이점이 있을까요?🤔

2024-05-06 17:01 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/ui/signUp/SignUpScreen.kt
> +    var phone by remember { mutableStateOf("") }
state는 viewModel에 있어야하지 않을까요??

2024-05-06 17:01 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/ui/signIn/SignInScreen.kt
> +    var password by remember { mutableStateOf("") }
Viewmodel에 옮겨주시면 좋을 것 같습니다

2024-05-06 17:01 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/ui/signIn/SignInScreen.kt
> +            onNavigateToHome.navigate("main")
👀

2024-05-06 17:01 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/ui/myPage/MyPageViewModel.kt
> +    }
onFailure 일 때도 사용자에게 회원가입이 실패했음을 알려야하지 않을까요?

2024-05-06 17:01 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/ui/myPage/MyPageViewModel.kt
> +    val infoState = _infoState.asStateFlow()
백킹 프로퍼티를 사용하셨군요! 💯  
- 백킹 프로퍼티를 사용하면 어떤 이점이 있을까요?
- 스토어드 프로퍼티와 백킹 프로퍼티의 차이는 무엇일까요?

2024-05-06 17:01 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/ui/home/HomeViewModel.kt
> +            }
성공했을때와 실패했을 때 분기처리 💯

2024-05-06 17:01 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/ui/home/HomeViewModel.kt
> +    private val followerService by lazy { ServicePool.followerService }
by lazy를 사용하신 이유가 있을까요? 👀

2024-05-06 17:01 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/ui/home/HomeScreen.kt
> +        }
😸

2024-05-06 17:01 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/ui/home/HomeScreen.kt
> +fun HomeScreen(homeViewModel: HomeViewModel = viewModel()) {
💯

2024-05-06 17:01 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/ui/home/HomeFriendProfile.kt
> +            model = profileImage,
AsyncImage 와 Image Component는 어떤 차이가 있을까요??

2024-05-06 17:01 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/data/network/AuthService.kt
> +    fun memberInfo(
해당 함수는 `get` prefix를 사용하지 않으셨군요..! 이유가 있을까요??  

> TMI: 저도 get 을 안붙이는걸 선호해요 🙂

2024-05-06 17:01 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/data/module/ApiFactory.kt
> +}
```suggestion
    inline fun <reified T> createFollower(): T = followerRetrofit.create()
}
```

클래스 타입을 매개변수로 넘기지 않아도 된답니다 💪

2024-05-06 17:01 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/data/module/ApiFactory.kt
> +    inline fun <reified T> createFollower(): T = followerRetrofit.create(T::class.java)
동료개발자가 createBase, createFollower 라는 네이밍을 보고, Retrofit 객체를 만드는걸 알 수 있을까요??
```suggestion
    inline fun <reified T> createBaseRetrofit(): T = baseRetrofit.createRetrofit(T::class.java)
    inline fun <reified T> createFollower(): T = followerRetrofit.create(T::class.java)
```

2024-05-06 17:01 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/data/model/SignUpState.kt
> +data class SignUpState(
해당 class는 왜 Dto postfix를 안붙이셨는지 궁금합니다 👀

2024-05-06 17:01 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/data/model/Profile.kt
>  data class Profile(
해당 class는 왜 Dto postfix를 안붙이셨는지 궁금합니다 👀

2024-05-06 17:01 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/data/model/ResponseInfoDto.kt
> +data class UserInfo(
해당 class는 왜 Dto postfix를 안붙이셨는지 궁금합니다 👀

2024-05-06 17:01 UTC, murjune commented on app/build.gradle
> +    implementation 'org.jetbrains.kotlinx:kotlinx-serialization-json:1.5.1'
주석으로 구분해주셨네요! 💯

2024-05-23 14:39 UTC, arinming reviewed
너무 늦게 답변 달아서 죄송합니다 🥹🥹🥹🥹🥹🥹🥹🥹🥹 합세를 컴포즈로 하고 있는데, 합세 하기 전에 리팩토링 했다면 훨씬 좋은 코드를 쓸 수 있었을텐데 하는 아쉬움이 있네욥.... 좋은 조언들 너무너무 감사하고 리팩토링하면서 반영하도록 하겠습니다!

2024-05-23 14:39 UTC, arinming commented on app/build.gradle
> +    annotationProcessor 'com.github.bumptech.glide:compiler:4.13.0'
어머나 코일만 사용하도록 하겠습니다!

2024-05-23 14:39 UTC, arinming commented on app/build.gradle
> +    implementation 'io.coil-kt:coil-compose:2.6.0'
Glide는 삭제하도록 하게씁니다..!

2024-05-23 14:39 UTC, arinming commented on app/build.gradle
>  }
이미지를 불러오는 라이브러리입니다! Glide 역할과 같아용 ㅎ ㅎ

2024-05-23 14:39 UTC, arinming commented on app/src/main/java/com/sopt/now/compose/data/module/ApiFactory.kt
> +    inline fun <reified T> createFollower(): T = followerRetrofit.create(T::class.java)
헉 네이밍 제안 너무 감사해요 섬세한 개발자가 되게씁니다!!!!!

2024-05-23 14:39 UTC, arinming commented on app/src/main/java/com/sopt/now/compose/data/module/ApiFactory.kt
> +}
reified으로 컴파일 타임에 타입 정보를 유지해줘서 가능한 거군욥..! 처음 알았습니다 ㅜㅜ 배워갑니다 🤩

2024-05-23 14:39 UTC, arinming commented on app/src/main/java/com/sopt/now/compose/data/module/AuthInterceptor.kt
> +            .build()
맞....습니당 ㅜㅠ 리팩토링하면서 수정하겠습니다,,,! Sharedpreferences로 구현해보려구욥!

2024-05-23 14:39 UTC, arinming commented on app/src/main/java/com/sopt/now/compose/data/network/AuthService.kt
> +    fun memberInfo(
어노테이션에서 @GET 어노테이션으로 명시가 되어있기도 하고, 코틀린 네이밍 관례상 get을 생략하는게 좋다고 들었던 것 같아요..! 준원님은 혹시 어떤 이유로 get 생략을 선호하는지 궁금합니당 ㅎㅎ 🫡

2024-05-23 14:39 UTC, arinming commented on app/src/main/java/com/sopt/now/compose/data/model/ResponseInfoDto.kt
> +data class UserInfo(
붙여야 겠네욥...!!!!!!!

2024-05-23 14:39 UTC, arinming commented on app/src/main/java/com/sopt/now/compose/data/model/SignUpState.kt
> +data class SignUpState(
여기는 API 통신에서 사용하지 않는 데이터 모델이라서 저렇게 명시했는데, 어떻게 작성하는 것이 좋을까요? 🥺

2024-05-23 14:39 UTC, arinming commented on app/src/main/java/com/sopt/now/compose/data/model/Profile.kt
>  data class Profile(
요 프로필은 view에 직접적으로 사용되고 API에는 사용되지 않아서 이렇게 명시했는데, 준원님은 어떻게 네이밍하시는지 궁금합니다!

2024-05-23 14:39 UTC, arinming commented on app/src/main/java/com/sopt/now/compose/ui/home/HomeViewModel.kt
> +    private val followerService by lazy { ServicePool.followerService }
지연초기화를 쓰면 뷰모델을 불러왔을 때 초기화되는 것이 아니라 실제로 해당 서비스 요청이 들어왔을 때 초기화된다고 들어서 사용했습니당 🫡 혹시 좋지 않은 방법일까용 ? 🥺

2024-05-23 14:39 UTC, arinming commented on app/src/main/java/com/sopt/now/compose/ui/home/HomeViewModel.kt
> +            )
좋아용! 이번 주차 과제로 해보게씁니다

2024-05-23 14:39 UTC, arinming commented on app/src/main/java/com/sopt/now/compose/ui/myPage/MyPageViewModel.kt
> +    val infoState = _infoState.asStateFlow()
백킹 프로퍼티로 캡슐화 해서, 외부에서 내부 프로퍼티에 직접 접근할 수 없게 할 수 있다는 이점이 있는 걸로 인지하고 있습니다! 스토어드 프로퍼티는 단순히 데이터를 저장하고, 필요할 때만 접근할 수 있고 백킹 프로퍼티는 외부에서의 변경을 방지한다...! 정도로 이해하고 있는데 공부 더 해보게씁니다..!

2024-05-23 14:39 UTC, arinming commented on app/src/main/java/com/sopt/now/compose/ui/myPage/MyPageViewModel.kt
> +    }
ResponseInfoDto 활용해서 에러 알릴 수 있게 추가해보겠습니다!

2024-05-23 14:39 UTC, arinming commented on app/src/main/java/com/sopt/now/compose/ui/signIn/SignInScreen.kt
> +    var password by remember { mutableStateOf("") }
넵 ! UI 관련 변수들은 ViewModel에 선언하기.. 메모메모

2024-05-23 14:39 UTC, arinming commented on app/src/main/java/com/sopt/now/compose/ui/signUp/SignUpScreen.kt
> +    var phone by remember { mutableStateOf("") }
여기도 옮기겠습니당..!!!!

2024-05-23 14:39 UTC, arinming commented on app/src/main/java/com/sopt/now/compose/ui/signUp/SignUpScreen.kt
> +            onNavigateToSignIn.navigate("sign_in")
상수화 항상 놓치네욥 ㅜㅠㅜ 상수화하면 유지보수하기 좋고, 추후 언어별로 앱을 지원할 때 필요하다고 들었습니다!

2024-05-23 14:39 UTC, arinming commented on app/src/main/java/com/sopt/now/compose/ui/signUp/SignUpScreen.kt
> +                id.length in 6..10 && password.length in 8..12 && nickname.isNotEmpty() && !nickname.contains(
흐엉어 ㅜㅜ 항상 놓치는 상수화.. 꼼꼼히 봐주셔서 감사해요

2024-05-23 14:39 UTC, arinming commented on app/src/main/java/com/sopt/now/compose/ui/signUp/SignUpViewModel.kt
> +    private val authService by lazy { ServicePool.authService }
위에 HomeViewModel과 동일한 이유입니당 🫣

2024-05-23 14:39 UTC, arinming commented on app/src/main/java/com/sopt/now/compose/ui/signUp/SignUpViewModel.kt
> +    private val _signUpState = MutableStateFlow(SignUpState(isSuccess = false, message = ""))
이전에 클린 아키텍처 공부하면서 간단히 정리한 내용인데욤..!

- LiveData를 통해 데이터 업데이트
    - 액티비티, 프래그먼트의 생명주기를 인식 → 메모리 누수 X
    - Observer를 통해 객체에 알려 UI와 데이터 상태 보장
    - LiveData는 Android 플랫폼에 종속적이기 때문에 UI가 없는 곳에서 LiveData를 사용하기가 어려움
        - 즉, 아키텍처 패턴 관점에서는 단점이 존재
        - Presentation 레이어에서는 사용 가능하나, Domain에서는 불가능
- StateFlow를 통해 데이터 업데이트
    - SharedFlow의 한 종류로, LiveData와 가장 가까움. LiveData를 대체 가능
    - 항상 오직 하나의 값을 가지고 있는 생성자로 초기상태가 필요함
    - 여러 collector를 지원하며 flow를 공유할 수 있음
        - collector의 개수에 상관 없이 구독하는 것의 최신 값을 받는다
        
따라서 StateFlow가 UI에 상관없이 구독하는 최신 값을 받아서 StateFlow로 구현하는 것을 지향하고 이씁니다. 잘못된 정보가 있다면 공유 부탁드려욤 🥹🥹🥹🥹

2024-05-23 14:39 UTC, arinming commented on app/src/main/java/com/sopt/now/compose/ui/signUp/SignUpViewModel.kt
> +    private val _signUpState = MutableStateFlow(SignUpState(isSuccess = false, message = ""))
이렇게 섬세하게 예외를 발견해주시다니 정말 감동임니다...

2024-05-23 14:39 UTC, arinming commented on app/src/main/java/com/sopt/now/compose/ui/signUp/SignUpViewModel.kt
> +                    response: Response<ResponseSignUpDto>,
오 너무 좋은 방법이네용 한번 해보겠습니당 🥹!

2024-05-23 14:39 UTC, arinming commented on app/src/main/java/com/sopt/now/compose/ui/signUp/SignUpViewModel.kt
> +                }
네엡 저도 케이스별로 에러메시지를 띄우는 건 필수....라고 생각합니다 ㅜㅜ 얼른 구현하겠습니다!

2024-06-07 12:21 UTC, merged

2024-06-17 16:49 UTC, murjune reviewed
@arinming  추가적인 남겨주신 질문 comment 달아놨습니다 😎

2024-06-17 16:49 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/data/model/Profile.kt
>  data class Profile(
아하 data 레이어에서만 사용하는 model 이였군요!  
dto 들과 같은 패키지에 있어 헷갈렸네요 😅

2024-06-17 16:49 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/data/model/SignUpState.kt
> +data class SignUpState(
dto 들과 같은 패키지에 있어 헷갈렸네요 😅

2024-06-17 16:49 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/data/network/AuthService.kt
> +    fun memberInfo(
전 getter() 함수를 넘어서 get 이라는 prefix 를 붙이는 컨벤션도 좋아하지 않는데요! 

이에 대해 정말 여러가지 이유가 있지만, 간단하게 한가지만 말씀드려볼게요 ㅎ ㅎ  
 getter, setter 는 [자바빈패턴](https://kihwan95.tistory.com/24)으로부터 유래되었어요. 자바빈패턴에서는 getter() 는 필드 값을 그대로 반환하고 있기에 해당 객체가 해당 field 값이 있음을 암시하고 있다고 생각해요.  

이는 클라이언트 입장에게 객체의 세부사항을 노출하는 것이기에 저는 선호하지 않습니다. 특히, 자바가 아닌 코틀린에서는 프로퍼티를 사용하고 있기에 더더욱 굳이 get prefix를 사용해야할까?? 라는 생각을 합니다. 😄  

> POJO 를 통해 getter 를 널리 퍼트린 Java 진영에서도 새로나온 record 문법을 보면, get prefix 를 권장하지 않습니다.

```kotlin
fun getA() // 해당 객체가 A라는 필드를 가지고 있겠군..! 
```

---  

 단순 네이밍이 아닌  getter() 사용을 지양해야하는 이유는 다음 블로그를 참고해주세요!  

[getter를 사용하는 대신 객체에 메시지를 보내자](https://tecoble.techcourse.co.kr/post/2020-04-28-ask-instead-of-getter/)

2024-06-17 16:49 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/data/network/AuthService.kt
> +    fun memberInfo(
참고로, get 을 메서드 네이밍에 사용하지 말자는 이야기는 [yegor bugayenko 의 엘레강트 오브젝트](https://jessyt.tistory.com/158) 책에서 유명해진 이야기 입니다.  

이 책도 추천드리는데요! 바쁘시면
[저자의 블로그글](https://www.yegor256.com/2014/09/16/getters-and-setters-are-evil.html)을 한 번 읽어보시는 것도 좋을 것 같네요 😄

2024-06-17 16:49 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/ui/home/HomeViewModel.kt
> +    private val followerService by lazy { ServicePool.followerService }
이미 ServicePool 에서 전역 서비스 객체를 선언해두셔서 여쭤본 겁니다!